# -*- coding: utf-8 -*-

"""Rephrasers to rephrase questions to increase diversity."""

import os
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Union

import numpy as np
from tqdm import tqdm

from chemcaption.featurize.text import Prompt, PromptCollection

__all__ = ["RePhraserBase", "SmolLMInstructRePhraser", "LLama2RePhraser"]

"""Base rephrasing class."""


class RePhraserBase(ABC):
    """RePhraser takes the Questions generated by featurizers and rephrases the
    question generating multiple alternative versions.

    Args:
        checkpoint (str): Huggingface model we want to use for rephrasing.
        device (str): Device where we want to run our model.
            Deafults to 'cpu'.
        samples (int): How many times we sample sample the rephrased question
            from the model.
        batch_size (int): How many prompts we want to process at
            one time. Deafults to 1.
        cache_dir (Optiona[str]): Location to save cache.
    """

    def __init__(
        self,
        checkpoint: str,
        device: str = "cpu",
        samples: int = 1,
        batch_size: int = 1,
        cache_dir: Optional[str] = None,
    ) -> None:
        """Instantiate class."""

        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.checkpoint = checkpoint
        self.device = device
        self.samples = samples
        self.batch_size = batch_size
        self.cache_dir = cache_dir

        if cache_dir:
            os.environ["HF_HOME"] = cache_dir

        self.model = AutoModelForCausalLM.from_pretrained(checkpoint).to(device)
        self.tokenizer = AutoTokenizer.from_pretrained(checkpoint)

    def generate_template(self, question: str) -> str:
        """Generate the template for rephrase the question.

        Args:
            question (str): Question we want to rephrase.

        Returns:
            str: rephrasing template.
        """

        messages = [
            {
                "role": "system",
                "content": ("You are an AI assistant only capable or rewriting questions "
                            "and replacing words with synonyms where possible!"),
            },
            {
                "role": "user",
                "content": ("Generate 3 alternative questions that ask the same "
                            "thing as the following question, using different wording "
                            "or phrasing.\n" + question),
            },
        ]
        messages = self.tokenizer.apply_chat_template(messages, tokenize=False)

        return messages

    @abstractmethod
    def extract_questions(self, output: str) -> List[str]:
        """Extracts the questions from the model output.

        Args:
            output (str): Output of the rephrasing model.

        Returns:
            List[str]: List of the rephrased questions.
        """

        raise NotImplementedError

    def filter_questions(self, prompt: Prompt, questions: List[str]) -> List[str]:
        """Filter the question. Remve duplicats and make sure the correct molecule
        is within the generte question.

        Args:
            prompt (Prompt): ChemCaption prompt.
            questions (List[str]): List of rephrased questions.

        Returns:
            List[str]: Filtered questions.
        """

        filtered = []

        for q in questions:
            if q in filtered:
                continue

            rep = None

            if isinstance(prompt.representation, list):
                rep = prompt.representation[0]
            else:
                rep = prompt.representation

            if rep in q:
                filtered.append(q)

        return filtered

    def rephrase(self, prompts: Union[PromptCollection, Prompt, List[Prompt]]) -> List[Dict]:
        """Rephrase the generated prompts.

        Args:
            prompts (Union[PrompCollection, Prompt, List[Prompt]): Prompts for rephrasing.

        Returns:
            List[Dict[str,str]]: List of rephrased prompts.
        """
        batches = []

        if isinstance(prompts, Prompt):
            batches = [prompts]
        if isinstance(prompts, PromptCollection):
            batches = prompts.prompts
        if isinstance(prompts, list):
            batches = prompts

        rephrased = []

        for i in tqdm(range(0, len(batches), self.batch_size), desc="Rephrasing..."):
            batch = batches[i: i + self.batch_size]

            input_text = [b.to_dict()["filled_prompt"] for b in batch]
            input_text = [self.generate_template(t) for t in input_text]
            inputs = self.tokenizer(
                input_text, padding=True, return_tensors="pt", padding_side="left"
            )["input_ids"].to(self.device)

            outs = self.model.generate(
                inputs,
                max_new_tokens=200,
                num_return_sequences=self.samples,
                temperature=0.2,
                top_p=0.9,
                do_sample=True,
            )
            outs = [self.tokenizer.decode(o) for o in outs]

            outs = np.array(outs)
            outs = np.reshape(outs, (-1, self.samples))

            for prompt, rep in zip(batch, outs):
                res = dict()
                prompt_dct = prompt.to_dict()
                res["original"] = prompt_dct["filled_prompt"]
                res["answer"] = prompt_dct["filled_completion"]
                res["alternative"] = []

                for r in rep:
                    res["alternative"] += self.extract_questions(r)

                res["alternative"] = self.filter_questions(prompt, res["alternative"])

                rephrased.append(res)

        return rephrased


"""Rephraser utilizing SmolLM."""


class SmolLMInstructRePhraser(RePhraserBase):
    """Uses SmolLMInstruct as REPhraser.
    Takes the Questions generated by featurizers and rephrases the
    question generating multiple alternative versions.

    Args:
        checkpoint (str): Huggingface model we want to use for rephrasing.
            Defaults to: 'HuggingFaceTB/SmolLM2-1.7B-Instruct'.
        device (str): Device where we want to run our model.
            Deafults to 'cpu'.
        samples (int): How many times we sample sample the rephrased question
            from the model.
        batch_size (int): How many prompts we want to process at
            one time. Deafults to 1.
        cache_dir (Optiona[str]): Location to save cache.
    """

    def __init__(
        self,
        checkpoint: str = "HuggingFaceTB/SmolLM2-1.7B-Instruct",
        device: str = "cpu",
        samples: int = 1,
        batch_size: int = 1,
        cache_dir: Optional[str] = None,
    ) -> None:
        """Instantiate class."""

        super().__init__(
            checkpoint=checkpoint,
            device=device,
            samples=samples,
            batch_size=batch_size,
            cache_dir=cache_dir,
        )

    def extract_questions(self, output: str) -> List[str]:
        """Extracts the questions from the model output.

        Args:
            output (str): Output of the rephrasing model.

        Returns:
            List[str]: List of the rephrased questions.
        """
        rephrased = output.split("<|im_start|>")[-1]
        rephrased_q = rephrased.split("\n")[1:]

        processed = []

        for r in rephrased_q:
            r = r[3:]
            r = r.replace("<|im_end|>", "")
            processed.append(r)
        return processed


"""Rephraser utilizing LLama2."""


class LLama2RePhraser(RePhraserBase):
    """Uses LLama2 as REPhraser.
    Takes the Questions generated by featurizers and rephrases the
    question generating multiple alternative versions.

    Args:
        checkpoint (str): Huggingface model we want to use for rephrasing.
            Defaults to: 'meta-llama/Llama-2-7b-chat-hf'.
        device (str): Device where we want to run our model.
            Deafults to 'cpu'.
        samples (int): How many times we sample sample the rephrased question
            from the model.
        batch_size (int): How many prompts we want to process at
            one time. Deafults to 1.
        cache_dir (Optiona[str]): Location to save cache.
    """

    def __init__(
        self,
        checkpoint: str = "meta-llama/Llama-2-7b-chat-hf",
        device: str = "cpu",
        samples: int = 1,
        batch_size: int = 1,
        cache_dir: Optional[str] = None,
    ) -> None:
        """Instantiate class."""
        
        super().__init__(
            checkpoint=checkpoint,
            device=device,
            samples=samples,
            batch_size=batch_size,
            cache_dir=cache_dir,
        )

        self.tokenizer.pad_token = "[PAD]"
        self.tokenizer.padding_side = "left"

    def extract_questions(self, output: str) -> List[str]:
        """Extracts the questions from the model output.

        Args:
            output (str): Output of the rephrasing model.

        Returns:
            List[str]: List of the rephrased questions.
        """

        output = output.split("\n\n")[-1]
        output_q = output.split("\n")

        processed = []

        for o in output_q:
            o = o[3:]
            o = o.replace("<unk>", "")
            o = o.replace("</s>", "")
            processed.append(o)

        return processed
