name: Tests

on:
  push:
    workflow_dispatch:

  pull_request:
    types: [ opened, synchronize, edited, ready_for_review ]
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -e ".[symmetry,tests,morfeus]"
      - name: Test for label uniqueness
        run: python src/chemcaption/export/pre_export_tests.py
      - name: Test with pytest and generate coverage file
        run:
          pytest tests/featurize/
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: coverage.xml
